// components/layout/footer.tsx
import { Link } from "components/link";
import { SOCIAL_ACCOUNTS } from "content/social-accounts";
import { FC } from "react";

type FooterProps = {};

export const Footer: FC<FooterProps> = ({}) => {
  return (
    <footer className="print:hidden">
      <div className="mx-auto max-w-6xl py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
        <div className="flex justify-center space-x-6 md:order-2">
          {Object.values(SOCIAL_ACCOUNTS).map(({ name, Icon, href }) => (
            <Link
              key={name}
              href={href}
              className="p-1 text-gray-400 hover:text-gray-500 d:text-gray-600 d:hover:text-gray-500"
            >
              <span className="sr-only">{name}</span>
              <Icon className="h-5 w-5" aria-hidden="true" />
            </Link>
          ))}
        </div>
        <div className="mt-8 md:order-1 md:mt-0">
          <small className="block text-center text-sm text-gray-400 d:text-gray-600">
            &copy; {new Date().getFullYear()} Aryan Vijaywargia, All rights reserved.
          </small>
        </div>
      </div>
    </footer>
  );
};

// src/app/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'] // or .css if you're using plain CSS
})
export class FooterComponent {
  currentYear = new Date().getFullYear();

  socialAccounts = [
    {
      name: "GitHub",
      href: "https://github.com/FelixTellmann",
      iconPath: "path_to_github_icon" // Replace with the path to your icon or SVG
    },
    {
      name: "Twitter",
      href: "https://twitter.com/FelixTellmann",
      iconPath: "path_to_twitter_icon" 
    },
    {
      name: "Facebook",
      href: "https://www.facebook.com/felix.tellmann/",
      iconPath: "path_to_facebook_icon" 
    },
    {
      name: "LinkedIn",
      href: "https://www.linkedin.com/in/felixtellmann",
      iconPath: "path_to_linkedin_icon" 
    }
  ];
}

<footer class="print:hidden">
    <div class="mx-auto max-w-6xl py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
        <div class="flex justify-center space-x-6 md:order-2">
            <a *ngFor="let account of socialAccounts" [href]="account.href"
                class="p-1 text-gray-400 hover:text-gray-500 d:text-gray-600 d:hover:text-gray-500">
                <span class="sr-only">{{ account.name }}</span>
                <!-- NOTE: You'll need to replace the below icon with your angular icons or image -->
                <img [src]="account.iconPath" alt="{{ account.name }}" class="{{account.iconPath}}" class="h-5 w-5" aria-hidden="true" />
            </a>
        </div>
        <div class="mt-8 md:order-1 md:mt-0">
            <small class="block text-center text-sm text-gray-400 d:text-gray-600">
                &copy; {{ currentYear }} Felix Tellmann, All rights reserved.
            </small>
        </div>
    </div>
</footer>
