// components/sections/timeline.tsx
import { useDebouncedEffect } from "components/_hooks/use-debounce-effect";
import clsx from "clsx";
import { TIMELINEOBJECT } from "content/timeline";
import { useInView } from "framer-motion";
import { FC, useEffect, useRef, useState } from "react";
import { scrollToX } from "utils/scroll-to";

type TimelineProps = {};

export const Timeline: FC<TimelineProps> = ({}) => {
  const [selected, setSelected] = useState("");
  const [initiated, setInitiated] = useState(false);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const [autoAnimate, setAutoAnimate] = useState(true);
  const [autoScroll, setAutoScroll] = useState(true);
  const inView = useInView(scrollContainerRef);

  useEffect(() => {
    if (!initiated && inView) {
      const container = scrollContainerRef.current as HTMLDivElement;
      setTimeout(
        () => {
          const year = Object.keys(TIMELINEOBJECT)[0];
          setInitiated(true);
          setSelected(`${year}-${0}`);
        },
        50
      );
    }
  }, [inView, initiated]);

  useDebouncedEffect(
    () => {
      if (!autoScroll || !inView) return;
      const [year, index] = selected.split("-");
      const keys = Object.keys(TIMELINEOBJECT);
      const values = Object.values(TIMELINEOBJECT);
      const yearLength = keys.length;
      const yearIndex = keys.findIndex((key) => key === year);
      const indexLength = TIMELINEOBJECT[year]?.length;
      const totalIndex =
        values.flat().findIndex((val) => new Date(val.date).getFullYear() === +year) + +index;

      const container = scrollContainerRef.current as HTMLDivElement;

      if (yearIndex + 1 === yearLength && +index + 1 === indexLength) return;

      const scrollTarget = totalIndex * 120;

      if (
        container.scrollLeft > scrollTarget - 120 ||
        scrollTarget > container.scrollLeft + container.clientWidth - 240
      ) {
        scrollToX(200, scrollTarget, container);
      }

      if (+index + 1 !== indexLength) {
        setSelected(`${year}-${+index + 1}`);
        return;
      }

      if (yearIndex + 1 !== yearLength && +index + 1 === indexLength) {
        setSelected(`${keys[yearIndex + 1]}-${0}`);
      }
    },
    2400,
    [selected, autoScroll, inView]
  );

  useDebouncedEffect(
    () => {
      setAutoScroll(true);
    },
    10000,
    [autoScroll]
  );

  return (
    <section className="mx-auto  max-w-6xl px-4 pb-16 md:px-8">
      <div className="-mx-4 flex h-96 overflow-x-auto px-6 py-4 xl:mx-0" ref={scrollContainerRef}>
        {Object.entries(TIMELINEOBJECT).map(([year, events], yearIndex, years) => (
          <div key={year} className="relative">
            <header className="absolute left-0 -translate-x-1/2 select-none text-xs font-semibold text-gray-400">
              {year}
            </header>
            <div
              className="mt-6 grid"
              style={{ gridTemplateColumns: `repeat(${events.length}, 120px)` }}
            >
              {events.map(({ heading, Icon, description }, index) => {
                return (
                  <section
                    key={heading}
                    className={clsx("relative", selected === `${year}-${index}` && "selected")}
                  >
                    <button
                      className=" absolute flex -translate-x-1/2 flex-col items-center px-3 hfa:outline-none"
                      onMouseOver={() => {
                        setAutoScroll(false);
                        setSelected(`${year}-${index}`);
                      }}
                      onPointerOver={() => {
                        setAutoScroll(false);
                        setSelected(`${year}-${index}`);
                      }}
                      onFocus={() => {
                        setAutoScroll(false);
                        setSelected(`${year}-${index}`);
                      }}
                      onClick={() => {
                        setAutoScroll(false);
                        setSelected(`${year}-${index}`);
                      }}
                    >
                      <span className="sr-only">{`${year} - ${heading}`}</span>
                      <div className="h-8 w-0.5 bg-gray-500 transition-all selected:h-[80px] selected:bg-sky-500"></div>
                      <Icon className="mt-2 h-5 w-5 text-gray-500 transition-all d:text-gray-400 selected:text-gray-900 d:selected:text-white" />
                    </button>
                    <div className="absolute left-px top-0 h-2.5 w-[119px] bg-[image:linear-gradient(90deg,transparent_0px,transparent_9px,var(--line-color)_10px,var(--line-color)_10px)] bg-[length:10px_10px] [--line-color:theme(colors.gray.500)]"></div>
                    <main
                      className={clsx(
                        "pointer-events-none relative mt-32 w-[17rem] opacity-0 transition-opacity  selected:pointer-events-auto selected:opacity-100",
                        yearIndex === 0 && index === 0 ? "" : "-translate-x-1/2 text-center"
                      )}
                    >
                      <h3 className="whitespace-nowrap font-semibold tracking-tight text-gray-800 d:text-gray-100">
                        {heading}
                      </h3>
                      <p className="text-[15px] font-medium leading-relaxed tracking-tight text-gray-500">
                        {description}
                      </p>
                    </main>
                  </section>
                );
              })}
            </div>
          </div>
        ))}

        <div className="relative">
          <header className="absolute left-0 -translate-x-1/2 text-xs font-semibold text-gray-400">
            Today
          </header>
          <div className="mt-6">
            <section className="relative">
              <div className="h-8 w-0.5 bg-gray-500 pb-4"></div>
            </section>
          </div>
        </div>
      </div>
    </section>
  );
};

// v1/src/app/time-line/time-line.component.ts
import { Component, ElementRef, EventEmitter, OnInit, Output, ViewChild } from '@angular/core';
import { TIMELINEOBJECT, TimelineEvent } from './time-line';
import { faCoffee } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-time-line',
  templateUrl: './time-line.component.html',
  styleUrls: ['./time-line.component.scss']
})

export class TimelineComponent implements OnInit {
  @ViewChild('scrollContainerRef', { static: true }) scrollContainerRef!: ElementRef<HTMLDivElement>;
  @Output() lastBarHighlighted = new EventEmitter<void>();
  public selected: string = ''; 
  initiated = false;
  autoAnimate = true;
  autoScroll = true;
  inView = false;

  TIMELINEOBJECT = TIMELINEOBJECT;
  faCoffee = faCoffee;
  selectedIconIndex: number | null = null;

  
  


  timelineEntries: any[] = Object.entries(this.TIMELINEOBJECT).map(
    ([year, events]) => ({
      year,
      events,
      descriptions: events.map(event => event.description),
      headings: events.map(event => event.heading),
      icons: events.map(event => event.Icon),
    })
  );
  selectedBarYear: any;
  selectedBarIndex: any;

  ngAfterViewInit(){
    this.scrollToSection();
  }


  public getCombinedValue(year: string, index: number): string {
    return `${year}-${index}`;
  }


  highlightVerticalBar(year: string, index: number) {
    const container = this.scrollContainerRef.nativeElement;
    const targetPosition = window.scrollX + container.clientWidth / 2 ; // Use window.scrollX to get the current scroll position
    const barElement = container.querySelector(`[data-bar="${year}-${index}"]`);
  
    if (barElement) {
      const barPosition = barElement.getBoundingClientRect().left + container.scrollLeft;
      const duration = 1000; // Duration of the scrolling animation in milliseconds
  
      this.scrollToX(duration, barPosition - targetPosition, container, () => {
        this.setSelected(`${year}-${index}`);
        if (this.isLastBar(year, index)) {
            this.lastBarHighlighted.emit();
        }
  
      });
    }
  }

  isLastBar(year: string, index: number): boolean {
    const lastEntry = this.timelineEntries[this.timelineEntries.length - 1];
    return year === lastEntry.year && index === lastEntry.events.length - 1;
  }
  

  async startHighlightingSequence() {
    if(this.timelineEntries){
      for(let entries=0; entries<this.timelineEntries.length; entries++){
        for (let index = 0; index < this.timelineEntries[entries].events.length; index++) {
         
          await this.delay(4000); 
        

          if(this.selectedBarYear){
            index = this.selectedBarIndex

            entries = this.timelineEntries.findIndex(entry => entry.year === this.selectedBarYear.toString());

            this.selectedBarYear=null;
            this.selectedBarIndex=null;
          }
          
          this.highlightVerticalBar(this.timelineEntries[entries].year, index);
          
                    
        }
      }
    }
  }

  delay(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
  



  ngOnInit() {
    setTimeout(() => {
      const year = Object.keys(this.TIMELINEOBJECT)[0];
      this.initiated = true;
      this.setSelected(`${year}-${0}`);
    }, 50);
  }

  onInViewChanged(inView: any) {
    if (!this.initiated && inView) {
      const container = this.scrollContainerRef.nativeElement;
      setTimeout(() => {
        const year = Object.keys(this.TIMELINEOBJECT)[0];
        this.initiated = true;
        this.setSelected(`${year}-${0}`);
      }, 50);
    }
  }

  setSelected(selected: string) {
    this.selected = selected;
    
  }

  scrollToSection() {
    const container = this.scrollContainerRef.nativeElement;
    const targetPosition = 500; // Replace 500 with the target scroll position you want to reach
    const duration = 1000; // Duration of the scrolling animation in milliseconds
  
    this.scrollToX(duration, targetPosition, container);
  }
  
  @Output() selectedBarValue = new EventEmitter<string>();

  onTimelineItemPointerOver(selected: any) {
    this.setSelected(selected);
    const parts = selected.split('-');

    this.selectedBarYear = parseInt(parts[0], 10); // Parse the year part
    this.selectedBarIndex = parseInt(parts[1], 10);

  }

  onTimelineItemFocused(selected: string) {
    this.setSelected(selected);
  }

  onAutoScrollDebounced() {
    this.autoScroll = true;
  }

  onAutoScrollTimeoutDebounced() {
    this.autoScroll = true;
  }

  scrollToX(duration: number, to: number, container: HTMLElement | Window = window, callback: () => void = () => {}) {
    const start = container instanceof HTMLElement ? container.scrollLeft : container.scrollX;

    const change = to - start;
    const startDate = new Date().getTime();

    const animateScroll = () => {
      const currentDate = new Date().getTime();
      const currentTime = currentDate - startDate;

      container.scrollTo(this.easeInOutQuad({ currentTime, start, change, duration }), 0);

      if (currentTime < duration) {
        requestAnimationFrame(animateScroll);
      } else {
        container.scrollTo(to, 0);
        callback();
      }
    };
    animateScroll();
  }

  private easeInOutQuad({ currentTime, start, change, duration }: any): number {
    currentTime /= duration / 2;
    if (currentTime < 1) {
      return (change / 2) * currentTime * currentTime + start;
    }
    currentTime--;
    return (-change / 2) * (currentTime * (currentTime - 2) - 1) + start;
  }
}


<section class="mx-auto  max-w-6xl px-4  md:px-8">
    <div class="-mx-4 flex overflow-x-auto py-4 px-6 xl:mx-0" (inView)="onInViewChanged($event)" #scrollContainerRef>
        <div *ngFor="let entry of timelineEntries ; let yearIndex = index;">
            <div class="relative">
                <header class="absolute left-0 -translate-x-1/2 select-none leading-4 font-semibold text-gray-400"
                    style="top: -1.5rem;">
                    {{ entry.year }}
                </header>
                <div class="mt-6 grid" [style.gridTemplateColumns]="'repeat(' + entry.events.length + ', 120px)'">
                    <div *ngFor="let event of entry.events; let index = index" class="relative"
                        [ngClass]="{ selected: selected === getCombinedValue(entry.year, index) }">
                        <button class="absolute flex -translate-x-1/2 flex-col items-center px-3 hfa:outline-none"
                            (mouseover)="onTimelineItemPointerOver(getCombinedValue(entry.year, index))"
                            (pointerover)="onTimelineItemPointerOver(getCombinedValue(entry.year, index))"
                            (focus)="onTimelineItemFocused(getCombinedValue(entry.year, index))"
                            (click)="setSelected(getCombinedValue(entry.year, index))">
                            <span class="sr-only">{{ entry.year }} -
                                {{ event.heading }}</span>
                            <div class="h-8 w-0.5 bg-gray-500 transition-all selected:h-[80px] selected:bg-sky-500">
                                <fa-icon [icon]="faCoffee" class="iconColor-lg"
                                    style="display: flex; justify-content: center; align-items: center;"
                                    [style.margin-top]=" selected===getCombinedValue(entry.year, index) ? '80px'
                                    : '20px'">
                                </fa-icon>

                            </div>
                        </button>
                        <div class=" absolute top-0 left-px h-2.5 w-[119px]
                                    bg-[image:linear-gradient(90deg,transparent_0px,transparent_9px,var(--line-color)_10px,var(--line-color)_10px)]
                                    bg-[length:10px_10px] [--line-color:theme(colors.gray.500)]"
                            [attr.data-bar]="getCombinedValue(entry.year, index)">
                        </div>
                        <main
                            class="pointer-events-none relative mt-28 w-[17rem] opacity-0 transition-opacity  selected:pointer-events-auto selected:opacity-100 -translate-x-1/2 text-center"
                            [ngClass]="{ '-translate-x-1/2 text-center': yearIndex != 0 || index != 0 }">
                            <h3 class="whitespace-nowrap font-semibold tracking-tight text-gray-800 d:text-gray-100">
                                {{ event.heading }}
                            </h3>
                            <p class="text-[15px] font-medium leading-relaxed tracking-tight text-gray-500">
                                {{ event.description }}
                            </p>
                        </main>
                    </div>
                </div>
            </div>
        </div>

        <div class="relative">
            <header class="absolute left-0 -translate-x-1/2 text-xs font-semibold text-gray-400">Today</header>
            <div class="mt-6">
                <section class="relative">
                    <div class="h-8 w-0.5 bg-gray-500 pb-4"></div>

                </section>
            </div>
        </div>
    </div>
</section>
