// components/scroll-gallery.tsx
import { ArrowLongLeftIcon, ArrowLongRightIcon } from "@heroicons/react/24/solid";
import { FC, PropsWithChildren, useCallback, useEffect, useRef, useState } from "react";
import { scrollToX } from "utils/scroll-to";

export const ScrollGallery: FC<
  PropsWithChildren<{ itemWidth: number; gapWidth: number; filter }>
> = ({ itemWidth, gapWidth, children, filter }) => {
  const scrollContainerRef = useRef<HTMLElement>(null);
  const [scrollNavigation, setScrollNavigation] = useState({ prev: false, next: true });
  const [isScrolling, setIsScrolling] = useState(false);

  const handleClickPrevious = useCallback(() => {
    if (isScrolling) return;
    const scrollContainer = scrollContainerRef.current as HTMLDivElement;
    scrollContainer.classList.remove("snap-x");
    setIsScrolling(true);
    scrollToX(
      200,
      Math.max(scrollContainer?.scrollLeft - itemWidth - gapWidth, 0),
      scrollContainer,
      () => {
        setIsScrolling(false);
        scrollContainer.classList.add("snap-x");
      }
    );
  }, [gapWidth, isScrolling, itemWidth]);

  const handleClickNext = useCallback(() => {
    if (isScrolling) return;
    const scrollContainer = scrollContainerRef.current as HTMLDivElement;
    scrollContainer.classList.remove("snap-x");
    setIsScrolling(true);
    scrollToX(200, scrollContainer.scrollLeft + itemWidth + gapWidth, scrollContainer, () => {
      setIsScrolling(false);
      scrollContainer.classList.add("snap-x");
    });
  }, [gapWidth, isScrolling, itemWidth]);

  useEffect(() => {
    const scrollContainer = scrollContainerRef.current as HTMLDivElement;
    const updateScrollNavigation = () => {
      setScrollNavigation(() => ({
        prev: scrollContainer?.scrollLeft > 0,
        next:
          scrollContainer.children[scrollContainer.children.length - 1]?.getBoundingClientRect()
            .right > window.innerWidth,
      }));
    };

    scrollContainer?.addEventListener("scroll", updateScrollNavigation);
    return () => {
      scrollContainer?.removeEventListener("scroll", updateScrollNavigation);
    };
  }, []);

  useEffect(() => {
    const scrollContainer = scrollContainerRef.current as HTMLDivElement;
    scrollContainer.classList.remove("snap-x");
    setIsScrolling(true);
    scrollToX(200, 0, scrollContainer, () => {
      setIsScrolling(false);
      scrollContainer.classList.add("snap-x");
    });
  }, [filter, gapWidth, itemWidth]);

  return (
    <>
      <div className="relative">
        <main
          className="sm:scrollbar-none group relative flex snap-x snap-mandatory scroll-pl-[max(var(--slider-padding),calc((100%-72rem)/2+var(--slider-padding)))] gap-8 overflow-x-auto px-[max(var(--slider-padding),calc((100%-72rem)/2+var(--slider-padding)))] py-12 [--slider-padding:2rem]"
          ref={scrollContainerRef}
        >
          {children}
        </main>
        <button
          className="absolute bottom-0 left-10 hidden items-center gap-2 px-4 py-2 text-sm text-gray-500 transition-all duration-75 disabled:text-gray-300 h:text-gray-900 disabled:h:text-gray-300 d:text-gray-300 d:disabled:text-gray-700 d:hfa:text-gray-50 d:disabled:hfa:text-gray-700 md:flex"
          onClick={handleClickPrevious}
          disabled={!scrollNavigation.prev}
        >
          <ArrowLongLeftIcon className="mt-0.5 h-5 w-5" />
          prev
        </button>

        <button
          className="absolute bottom-0 right-10 hidden items-center gap-2 px-4 py-2 text-sm text-gray-500 transition-all duration-75 disabled:text-gray-300 h:text-gray-900 h:text-gray-900 disabled:h:text-gray-300 d:text-gray-300 d:disabled:text-gray-700 d:hfa:text-gray-50 d:disabled:hfa:text-gray-700 md:flex"
          onClick={handleClickNext}
          disabled={!scrollNavigation.next}
        >
          next
          <ArrowLongRightIcon className="mt-0.5 h-5 w-5" />
        </button>
      </div>
    </>
  );
};

// src/app/scroll-gallery/scroll-gallery.component.ts
import { Component, ElementRef, HostListener, Input, OnInit, ViewChild } from '@angular/core';

interface ScrollNavigation {
  prev: boolean;
  next: boolean;
}
interface EaseInOutQuadOptions {
  change: number;
  currentTime: number;
  duration: number;
  start: number;
}

const easeInOutQuad = ({ currentTime, start, change, duration }: EaseInOutQuadOptions): number => {
  let newCurrentTime = currentTime;
  newCurrentTime /= duration / 2;

  if (newCurrentTime < 1) {
    return (change / 2) * newCurrentTime * newCurrentTime + start;
  }

  newCurrentTime -= 1;
  return (-change / 2) * (newCurrentTime * (newCurrentTime - 2) - 1) + start;
}

const scrollToX = (
  duration: number,
  to: number,
  container: HTMLElement | Window = window,
  callback: () => void = () => {}
): void => {
  const start = container instanceof HTMLElement ? container.scrollLeft : container.scrollX;

  const change = to - start;
  const startDate = new Date().getTime();

  const animateScroll = () => {
    const currentDate = new Date().getTime();
    const currentTime = currentDate - startDate;

    container.scrollTo(
      easeInOutQuad({
        currentTime,
        start,
        change,
        duration,
      }),
      0
    );

    if (currentTime < duration) {
      requestAnimationFrame(animateScroll);
    } else {
      container.scrollTo(to, 0);
      callback();
    }
  };
  animateScroll();
};

@Component({
  selector: 'app-scroll-gallery',
  templateUrl: './scroll-gallery.component.html',
  styleUrls: ['./scroll-gallery.component.scss']
})
export class ScrollGalleryComponent implements OnInit {
  @ViewChild('scrollContainer') scrollContainerRef!: ElementRef;

  scrollNavigation: ScrollNavigation = { prev: false, next: true };
  isScrolling = false;

  @Input() itemWidth!:number;
  // itemWidth = 0;
  @Input() gapWidth!:number;
  filter = 'All Projects'; // Set the initial filter value

  constructor() { }

  ngOnInit(): void {
    this.updateScrollNavigation();
    this.scrollToBeginning();
  }

  private getScrollDirection(scrollContainer: HTMLElement): 'left' | 'right' {
    const previousScroll = Number(scrollContainer.dataset['previousScroll']) || 0;
    if (scrollContainer.scrollLeft < previousScroll) {
      // Scrolling to the left
      scrollContainer.dataset['previousScroll'] = scrollContainer.scrollLeft.toString();
      return 'left';
    } else {
      // Scrolling to the right or no horizontal scroll change
      scrollContainer.dataset['previousScroll'] = scrollContainer.scrollLeft.toString();
      return 'right';
    }
  }

  @HostListener('scroll', ['$event'])
  onScroll(event:Event): void {
    const scrollContainer = this.scrollContainerRef.nativeElement as HTMLElement;
   
      this.updateScrollNavigation();
   
  }
  handleClickPrevious(): void {
    // if (this.isScrolling) return;
    const scrollContainer = this.scrollContainerRef.nativeElement as HTMLDivElement;
    scrollContainer.classList.remove('snap-x');
    // this.isScrolling = true;

    scrollToX(
      200,
      Math.max(scrollContainer.scrollLeft - this.itemWidth - this.gapWidth, 0),
      scrollContainer,
      () => {
        scrollContainer.classList.add('snap-x');
        this.updateScrollNavigation();
      }
    );
  }

  handleClickNext(): void {

    const scrollContainer = this.scrollContainerRef.nativeElement as HTMLDivElement;
    scrollContainer.classList.remove('snap-x');

    scrollToX(200, scrollContainer.scrollLeft + this.itemWidth + this.gapWidth, scrollContainer, () => {
      scrollContainer.classList.add('snap-x');
      this.updateScrollNavigation();
    });
  }

  updateScrollNavigation(): void {
    if(this.scrollContainerRef!= null){
      const scrollContainer = this.scrollContainerRef.nativeElement as HTMLDivElement;
    this.scrollNavigation = {
      prev: scrollContainer.scrollLeft > 0,
      next: scrollContainer.children[scrollContainer.children.length - 1]?.getBoundingClientRect().right > window.innerWidth
    };
    }
    
  }

  scrollToBeginning(): void {
    if(this.scrollContainerRef!= null){
      const scrollContainer = this.scrollContainerRef.nativeElement as HTMLDivElement;
      scrollContainer.classList.remove('snap-x');
      
  
      scrollToX(200, 0, scrollContainer, () => {
        scrollContainer.classList.add('snap-x');
      });
    }
    }
}

<div class="relative">
    <main
      class="sm:scrollbar-none group relative flex snap-x snap-mandatory scroll-pl-[max(var(--slider-padding),calc((100%-72rem)/2+var(--slider-padding)))] gap-8 overflow-x-auto py-12 px-[max(var(--slider-padding),calc((100%-72rem)/2+var(--slider-padding)))] [--slider-padding:2rem]"
      #scrollContainer
    >
      <ng-content></ng-content>
    </main>
    <button
      class="absolute left-10 bottom-0 hidden items-center gap-2 py-2 px-4 text-sm text-gray-500 transition-all duration-75 disabled:text-gray-300 h:text-gray-900 disabled:h:text-gray-300 d:text-gray-300 d:disabled:text-gray-700 d:hfa:text-gray-50 d:disabled:hfa:text-gray-700 md:flex"
      [class.disabled]="!scrollNavigation.prev"
  (click)="handleClickPrevious()"
  [disabled]="!scrollNavigation.prev"
    >
      <svg class="mt-0.5 h-5 w-5">
        <!-- Add the SVG icon for previous here -->
      </svg>
      prev
    </button>
  
    <button
      class="absolute right-10 bottom-0 hidden items-center gap-2 py-2 px-4 text-sm text-gray-500 transition-all duration-75 disabled:text-gray-300 h:text-gray-900 h:text-gray-900 disabled:h:text-gray-300 d:text-gray-300 d:disabled:text-gray-700 d:hfa:text-gray-50 d:disabled:hfa:text-gray-700 md:flex"
      (click)="handleClickNext()"
      [disabled]="!scrollNavigation.next"
    >
      next
      <svg class="mt-0.5 h-5 w-5">
        <!-- Add the SVG icon for next here -->
      </svg>
    </button>
  </div>
