// components/sections/about.tsx
import { useAchievements } from "components/achievements";
import { useTooltipStore } from "components/_stores/tooltip-store";
import { Image } from "components/image";
import { ABOUT } from "content/about";
import { FC, useCallback, useRef, useState } from "react";

type AboutProps = {};

export const About: FC<AboutProps> = (props) => {
  const imageRef = useRef<HTMLImageElement[]>([]);
  const [focusImageIndex, setFocusImageIndex] = useState(0);
  const [images, setImages] = useState(ABOUT.images);
  const [tooltip, setTooltip] = useTooltipStore();
  const buttonRef = useRef<HTMLButtonElement>(null);
  const { trackAchievementEvent } = useAchievements();

  const handleImageClick = useCallback(() => {
    setTooltip(false);
    if (focusImageIndex === images.length - 1) {
      trackAchievementEvent({ type: "about:cycle-complete" });
      setFocusImageIndex((current) => current + 1);
      setImages((current) => current.sort(() => 0.5 - Math.random()));
      setTimeout(
        () => {
          setFocusImageIndex(0);
          setTooltip(true);
          const trigger = new Event("mouseover");
          setTimeout(
            () => {
              buttonRef.current?.dispatchEvent(trigger);
            },
            50
          );
        },
        350
      );
    }

    if (focusImageIndex < images.length - 1) {
      setFocusImageIndex((current) => current + 1);
      setTimeout(
        () => {
          setTooltip(true);
          const trigger = new Event("mouseover");
          setTimeout(
            () => {
              buttonRef.current?.dispatchEvent(trigger);
            },
            50
          );
        },
        50
      );
    }
  }, [focusImageIndex, images.length, setTooltip, trackAchievementEvent]);

  return (
    <section id="about" className="-mt-12 overflow-hidden pt-12">
      {/* Section Header */}
      <header className="mx-auto mb-8 grid w-full max-w-6xl px-4 md:px-8">
        <div className="heading-pre">Get to Know Me</div>
        <h1 className="heading-2xl -ml-1">About Me</h1>
      </header>

      <div className="mx-auto flex max-w-6xl flex-col justify-center gap-16 px-4 pb-16 md:px-8 lg:grid lg:grid-cols-[540px_auto] lg:pt-8">
        <button
          ref={buttonRef}
          className="group relative mx-auto mb-12 aspect-3/2 max-h-[405px] w-full max-w-[540px] flex-1 hfa:outline-none lg:mb-auto  lg:mr-0 lg:aspect-4/3"
          onClick={handleImageClick}
          type="button"
          data-event="mouseover"
          data-tip={images[focusImageIndex]?.alt}
        >
          <span className="sr-only">Cycle through Images</span>
          {images.map(({ src, alt }, index) => {
            return (
              <Image
                maxWidth={540}
                src={src}
                alt={alt}
                key={alt}
                width={2000}
                height={1500}
                sizes="(min-width: 580px) 540px, 400px"
                preload
                priority={index === 0}
                className="absolute left-0 top-0 rounded-xl border-2 border-gray-50/80 object-cover !opacity-0 shadow-lg shadow-gray-700/5 transition-all duration-300 group-focus-visible:border-sky-500 d:border-gray-600/80"
                data-about-image-index={index}
                onLoadingComplete={() =>
                  document
                    .querySelectorAll(`[data-about-image-index="${index}"]`)
                    .forEach((img) => img.classList.remove("!opacity-0"))
                }
                style={{
                  transform:
                    focusImageIndex > index
                      ? `translate(-700px, -${(index % 4) * 60 + 25}px) rotate(${
                          (index % 4) * (index % 2 === 0 ? 0.5 : -1.2) * 3
                        }deg)`
                      : `rotate(${(index % 4) * (index % 2 === 0 ? 0.5 : -1.2) * 3}deg)`,
                  zIndex: -index,
                  filter: focusImageIndex !== index ? "grayscale(80)" : "",
                  opacity: focusImageIndex > index ? "0" : "1",
                }}
              />
            );
          })}
          <div className="relative -z-50 h-full w-full -rotate-6 rounded-xl bg-gray-200/80"></div>
        </button>
        <section className="spacing-8">
          <header className="grid max-w-xl grid-cols-2 gap-4 text-center sm:grid-cols-4 sm:text-left">
            {ABOUT.stats.map(({ statistic, caption, tooltip }, index) => {
              return (
                <figure
                  key={caption + index}
                  data-tip={tooltip}
                  className="cursor-help select-none spacing-1"
                >
                  <span className="bg-gradient-to-r from-cyan-500 to-blue-600 bg-clip-text text-4xl font-extrabold tracking-tighter text-transparent">
                    {statistic}
                  </span>
                  <figcaption className="text-[15px] font-semibold tracking-tight text-gray-400 d:text-gray-300/80">
                    {caption}
                  </figcaption>
                </figure>
              );
            })}
          </header>
          <main className="tracking tight max-w-3xl leading-relaxed text-gray-500 d:text-gray-100/70 [&>p+p]:mt-4">
            {ABOUT.description}
          </main>
        </section>
      </div>
    </section>
  );
};

// src/app/about/about.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { ABOUT } from './ABOUT';
import { HeroHeightService } from '../hero-height.service';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
})
export class AboutComponent {
  @ViewChild('buttonRef') buttonRef!: ElementRef<HTMLButtonElement>;
  focusImageIndex:number = 0;
  image:any= ABOUT.images[0]; 
  index:number = 0;
  rangeIndex:string="";
  ABOUT = ABOUT;

  trackRangeValue(newValue: string) {
    // this.items.push(newItem);
    this.rangeIndex = newValue;
  }


  @ViewChild('heroSection', { static: true }) heroSection!: ElementRef;

  constructor(private heroHeightService: HeroHeightService) {}

  ngAfterViewInit() {
    const heroSectionHeight = this.heroSection.nativeElement.clientHeight;
    this.heroHeightService.setHeroHeight(heroSectionHeight);
  }


}

<section id="portfolio" class="portfolio-preview min-h-full spacing-4" #heroSection>
  <header class="mx-auto grid w-full max-w-6xl px-4 md:px-8">
    <div class="heading-pre">About Me</div>
    <h1 class="heading-2xl -ml-1">Random stuff about me</h1>
  </header>

  <section id="about" class="-mt-12 overflow-hidden pt-12">
    <div style="max-width: 85rem;"
      class="mx-auto flex flex-col justify-center gap-16 px-4 pb-16 md:px-8 lg:grid lg:grid-cols-[540px_auto] lg:pt-16">
      <button #buttonRef
        class="group relative mx-auto mb-12 aspect-3/2 max-h-[405px] w-full max-w-[540px] flex-1 hfa:outline-none lg:mb-auto  lg:mr-0 lg:aspect-4/3"
        type="button" data-event="mouseover" [attr.data-tip]="image?.alt">
        <!-- [attr.data-tip]="images[focusImageIndex]?.alt" -->
        <!-- <span class="sr-only">Cycle through Images</span> -->

        <app-image [maxWidth]="540" [maxHeight]="400" [src]="image.src" [alt]="image.alt" [key]="image.alt"
          [width]="2000" [height]="1500" sizes="(min-width: 580px) 540px, 400px" [preload]="true"
          [class]="'absolute left-0 top-0 rounded-xl border-2 border-gray-50/80 object-cover shadow-lg shadow-gray-700/5 transition-all duration-300 group-focus-visible:border-sky-500 d:border-gray-600/80'"
          [attr.data-about-image-index]="index" [style.transform]="
              focusImageIndex > index
                ? 'translate(-700px, -' + (index % 4) * 60 + 25 + 'px) rotate(' + (index % 4) * (index % 2 === 0 ? 0.5 : -1.2) * 3 + 'deg)'
                : 'rotate(' + (index % 4) * (index % 2 === 0 ? 0.5 : -1.2) * 3 + 'deg)'" [style.zIndex]="-index"
          [style.filter]="focusImageIndex !== index ? 'grayscale(80)' : ''"
          [style.opacity]="focusImageIndex > index ? '0' : '1'" [aspectRatio]="4/3"></app-image>
        <div class="relative -z-50 h-full w-full -rotate-6 rounded-xl bg-gray-200/80"></div>
      </button>
      <section class="spacing-8 flex flex-row">
        <div class="flex flex-col gap-3">
          <header class="grid max-w-xl grid-cols-2 gap-4 text-center sm:grid-cols-4 sm:text-left">
            <figure *ngFor="let item of ABOUT.stats; let i = index" class="cursor-help select-none spacing-1">
              <span
                class="bg-gradient-to-r from-cyan-500 to-blue-600 bg-clip-text text-4xl font-extrabold tracking-tighter text-transparent"
                [innerHTML]="item.statistic">
                <!-- {{ item.statistic }} -->
              </span>
              <figcaption class="text-[15px] font-semibold tracking-tight text-gray-400 d:text-gray-300/80"
                [innerHTML]="item.caption">
                <!-- {{ item.caption }} -->
              </figcaption>
            </figure>
          </header>
          <div style="display:flex; flex-direction: row;">
            <div>
              <ng-container *ngIf="rangeIndex === 'Small'">
                <main class="tracking tight max-w-3xl leading-relaxed text-gray-500 d:text-gray-100/70 [&>p+p]:mt-4"
                  [innerHTML]="ABOUT.description1">
                </main>
              </ng-container>
              <ng-container *ngIf="rangeIndex === 'Medium' || rangeIndex=== ''">
                <main class="tracking tight max-w-3xl leading-relaxed text-gray-500 d:text-gray-100/70 [&>p+p]:mt-4"
                  [innerHTML]="ABOUT.description2">
                </main>
              </ng-container>
              <ng-container *ngIf="rangeIndex === 'Large'">
                <main class="tracking tight max-w-3xl leading-relaxed text-gray-500 d:text-gray-100/70 [&>p+p]:mt-4"
                  [innerHTML]="ABOUT.description3">
                </main>
              </ng-container>
            </div>
            <!-- <div style="transform: rotateZ(90deg); display: flex; justify-content: center; align-items: center;">
              <app-range-slider (sliderVal)="trackRangeValue($event)"></app-range-slider>
            </div> -->
          </div>
        </div>

      </section>
    </div>
    <app-time-line></app-time-line>

  </section>
</section>
