// content/hero.tsx
// @ts-ignore
import heroCode from "!!raw-loader!content/code-blocks/hero.tsx"; // Adding `!!` to a request will disable all loaders specified in the configuration
import { SiPython } from "@react-icons/all-files/si/SiPython";
import { SiTensorflow } from "@react-icons/all-files/si/SiTensorflow";
import { SiTypescript } from "@react-icons/all-files/si/SiTypescript";
import { SiAngular } from "@react-icons/all-files/si/SiAngular";
import { Link } from "components/link";
import party from "party-js";

export const HERO = {
  pre: "Welcome to my site.",
  heading: (
    <>
      I'm <strong>Aryan Vijaywargia</strong>, a Fullstack Engineer.
    </>
  ),
  tech: [
    {
      name: "Python",
      Icon: ({ className }) => <SiPython className={className} />,
    },
    {
      name: "TensorFlow",
      Icon: ({ className }) => <SiTensorflow className={className} />,
    },
    {
      name: "TypeScript",
      Icon: ({ className }) => <SiTypescript className={className} />,
    },
    {
      name: "Angular",
      Icon: ({ className }) => <SiAngular className={className} />,
    },
  ] as const,
  body: (
    <>
      I love building intelligent systems that take things to the next level - creating ML models for
      real-world applications, automated data pipelines, and stunning user-experiences
      that make you feel{" "}
      <em
        className="relative cursor-pointer before:absolute b:bottom-0 b:-z-10 b:h-3 b:w-full b:-rotate-2 b:animate-hint-hint b:bg-pink-400/70 b:blur-sm d:b:bg-pink-600"
        onClick={(e) => {
          e.currentTarget.classList.remove("before:absolute");
          party.confetti(e.currentTarget, { count: 40 });
        }}
      >
        WOW!
      </em>
      .<span className="mt-4 block" />I am always keen to learn and explore new technologies,
      frameworks and programming languages. Currently, I'm exploring{" "}
      <Link target="_blank" href="https://pytorch.org/" className="underline hfa:text-sky-500">
        PyTorch
      </Link>{" "}
      and{" "}
      <Link href="https://mlflow.org" target="_blank" className="underline hfa:text-sky-500">
        MLFlow
      </Link>
      .
    </>
  ),
  cta1: {
    href: "/resume",
    name: "Resume",
  },
  cta2: {
    href: "mailto:aryanvijaywargia@gmail.com",
    name: "Contact Me",
  },
  code: `${heroCode}`,
};

// src/app/hero/hero.component.ts
import { Component } from '@angular/core';
// import { SiNodeDotJs } from '@angular-icons/all-files/si/SiNodeDotJs';
// import { SiReact } from '@angular-icons/all-files/si/SiReact';
// import { SiShopify } from '@angular-icons/all-files/si/SiShopify';
// import { SiTailwindcss } from '@angular-icons/all-files/si/SiTailwindcss';
// import { TECH } from 'content/tech-stack';
import * as party from 'party-js';
import { IconService } from '../hero-section/icon.service';

@Component({
  selector: 'app-hero',
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.scss'],
})
export class HeroComponent {

  iconNames: string[] = ['cib-angular', 'cib-tensorflow', 'cib-typescript', 'cib-dot-net'];  

  constructor(public iconService: IconService) {}

  ngOnInit(): void {
    this.iconService.loadIcons(this.iconNames)
      .then(() => {
        console.log("Icons have been loaded and are ready to be displayed")
      })
      .catch(error => {
        console.error('Failed to load icons:', error);
      });
  }

  tech = [
    {
      name: 'Angular',
      Icon: 'cib-angular',
    },
    {
      name: 'Node.js',
      Icon: 'cib-tensorflow',
    },
    {
      name: 'Tailwind',
      Icon: 'cib-typescript',
    },
    {
      name: 'Shopify',
      Icon: 'cib-dot-net',
    },
  ] as const;

  // iconInjector = Injector.create({
  //   providers: [{ provide: 'className', useValue: 'your-class-name' }],
  // });

  onWowClick(event: Event) {
    const target = event.currentTarget as HTMLElement;
    target.classList.remove('before:absolute');
    party.confetti(target, { count: 40 });
  }

}

<!-- <section class="hero relative overflow-hidden pb-40">
    <div class="relative mx-auto flex max-w-6xl grid-cols-3 flex-col gap-8 gap-y-16 px-4 py-16 md:py-32 md:px-8 lg:grid">
      <section class="col-span-2">
        <header>
          <div class="heading-pre">{{ HERO.pre }}</div>
          <h1 class="heading-hero">{{ HERO.heading }}</h1>
          <ul class="sm:scrollbar-none -mx-4 mb-2 flex items-center gap-6 overflow-x-auto px-4 pb-2 text-[15px] font-medium">
            <li *ngFor="let tech of HERO.tech" class="flex items-center gap-2 text-gray-500 d:text-gray-400">
              <i [class]="'h-7 w-7 text-gray-400 d:text-gray-300/80 ' + tech.Icon"></i>
              {{ tech.name }}
            </li>
          </ul>
        </header>
        <main>
          <p class="mb-3 max-w-prose font-normal text-gray-500 d:text-gray-400 md:text-lg md:tracking-tight">{{ HERO.body }}</p>
          <p class="mb-3 max-w-xl font-normal text-gray-500 md:text-lg md:tracking-tight"></p>
        </main>
      </section>
    </div>
  </section> -->


  <div>
    <p>Welcome to my site.</p>
    <h1>
      I'm <strong>Felix Tellmann</strong>, a Fullstack developer.
    </h1>
    <ul>
      <li *ngFor="let techItem of tech">
        {{ techItem.name }}
        <ng-container *ngIf="iconService.getIcon(techItem.Icon)">
            <!-- Using the SVG content directly -->
            <div [innerHTML]="iconService.getIcon(techItem.Icon)"></div>
    
            <!-- Or, you can also create a custom component and pass the SVG content as an input -->
            <!-- <app-custom-icon [iconContent]="iconService.getIcon(iconName)"></app-custom-icon> -->
          </ng-container>
    
      </li>
    </ul>
    <p>
      I love writing code that takes things next level, creating highly performant websites,
      automated API integrations, building my own dev-tools, and creating stunning user-experiences that make you feel
      <em
        class="relative cursor-pointer before:absolute b:bottom-0 b:-z-10 b:h-3 b:w-full b:-rotate-2 b:animate-hint-hint b:bg-pink-400/70 b:blur-sm d:b:bg-pink-600"
        (click)="onWowClick($event)"
      >
        WOW!
      </em>
    </p>
    <p>I am always keen to learn and explore new technologies, frameworks, and programming languages. Currently, I'm learning about <span>.</span></p>
  </div>
