// src/app/image/image.component.ts
import { Component, Input } from '@angular/core';
import { PhoneComponent } from '../phone/phone.component';

@Component({
  selector: 'app-image',
  templateUrl: './image.component.html',
})
export class ImageComponent {
  @Input() pixelDensity = 1;
  @Input() preload!: boolean;
  @Input() src!: string;
  @Input() alt!: string;
  @Input() key!: string;
  @Input() width!: any;
  @Input() height!: any;
  @Input() maxWidth!: any;
  @Input() maxHeight!: any;
  @Input() aspectRatio!: number;


  ngOnInit(){
    
  }

  calcSrc(){
    const imgSrc = typeof this.src === 'string' ? this.src.replace(/^(http:)?\/\//, 'https://') : this.src
    return imgSrc;
  }

  calculateWidth(): number {
    const aspect = this.aspectRatio ?? +this.width / +this.height;
    const maxWidth = this.maxWidth ? +this.maxWidth : this.maxHeight ? +this.maxHeight * aspect : +this.width;
    return Math.round(maxWidth * this.pixelDensity);
  }

  calculateHeight(): number {
    const aspect = this.aspectRatio ?? +this.width / +this.height;
    const maxHeight = this.maxHeight ? +this.maxHeight : this.maxWidth ? +this.maxWidth / aspect : +this.height;
    return Math.round(maxHeight * this.pixelDensity);
  }

  get objectFitStyle(): string {
    // Set the object-fit style based on the aspect ratio
    if (this.aspectRatio) {
      if (this.aspectRatio > 1) {
        return 'contain';
      } else {
        return 'cover';
      }
    }
    return 'initial';
  }
}

<img
      [src]="calcSrc()"
      [width]="calculateWidth()"
      [height]="calculateHeight()"
      [style.objectFit]="objectFitStyle"
      [style.maxWidth]="maxWidth ? maxWidth + 'px' : undefined"
      [style.maxHeight]="maxHeight ? maxHeight + 'px' : undefined"
      [style.aspectRatio]="aspectRatio"
>

// components/image.tsx
import { ImageProps } from "next/dist/client/future/image";
import NextImage from "next/future/image";
import { FC } from "react";
import { SetRequired } from "type-fest";

export const Image: FC<
  SetRequired<Omit<ImageProps, "src">, "width" | "height"> & {
    aspectRatio?: number;
    maxHeight?: number;
    maxWidth?: number;
    pixelDensity?: number;
    preload?: boolean;
    src?: ImageProps["src"];
  }
> = ({ pixelDensity = 1, preload, ...props }) => {
  const { src, width, height, maxWidth, maxHeight, aspectRatio, ...rest } = props;

  const aspect = aspectRatio ?? +width / +height;

  if (!src || src === "undefined") {
    return null;
  }

  return (
    <NextImage
      {...rest}
      priority={preload || rest.priority}
      placeholder={!preload ? "blur" : undefined}
      blurDataURL={
        typeof src === "string" && !preload
          ? `/_next/image?url=${encodeURIComponent(
              src.replace(/^(http:)?\/\//, "https://")
            )}&w=32&q=1`
          : undefined
      }
      src={typeof src === "string" ? src.replace(/^(http:)?\/\//, "https://") : src}
      width={Math.round(
        +(maxWidth ? maxWidth : maxHeight ? maxHeight * aspect : width) * pixelDensity
      )}
      height={Math.round(
        +(maxHeight ? maxHeight : maxWidth ? maxWidth / aspect : height) * pixelDensity
      )}
    />
  );
};
